In [2]:
# Linear Algebra Continued - Systems, Transformations & Eigenvalues

import numpy as np

print("Linear Algebra Continued: Systems, Transformations & Eigenvalues\n")

# 1. Solving Linear Systems (Ax = b)
A = np.array([[3, 2], [1, -1]])
b = np.array([8, 1])
print("Matrix A:\n", A)
print("Vector b:", b)

# Solve using NumPy
x = np.linalg.solve(A, b)
print("Solution x =", x)

# Verification
print("Verification (A @ x):", np.dot(A, x))

# 2. Matrix Transformations & Eigenvalues
matrix = np.array([[2, 1], [1, 2]])
print("\nTransformation Matrix:\n", matrix)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# 3. Determinant & Inverse (useful for transformations)
det = np.linalg.det(matrix)
print("Determinant:", det)

if det != 0:
    inv = np.linalg.inv(matrix)
    print("Inverse:\n", inv)

print("\n✅ Done")

Linear Algebra Continued: Systems, Transformations & Eigenvalues

Matrix A:
 [[ 3  2]
 [ 1 -1]]
Vector b: [8 1]
Solution x = [2. 1.]
Verification (A @ x): [8. 1.]

Transformation Matrix:
 [[2 1]
 [1 2]]
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Determinant: 2.9999999999999996
Inverse:
 [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]

✅ Done
